apiVersion: apps/v1
kind: Deployment
metadata:
  name: akka-http-k8s-deployment
  labels:
    app: akka-http-k8s
spec:
  selector:
    matchLabels:
      app: akka-http-k8s
  replicas: 3
  template:
    metadata:
      labels:
        app: akka-http-k8s
    spec:
      containers:
      - name: akka-http-k8s
        image: "127.0.0.1:5000/akka-http-k8s"
        ports:
        - containerPort: 80
        readinessProbe:
         httpGet:
           port: 8080
           path: /check